#!/bin/sh
# Print an audit watch for every user's .ssh directory.
#
# Audit watches take no wildcards, so /home/*/.ssh cannot be expressed as one
# rule. This prints one line per existing home directory:
#
#   sudo deploy/gen-sshkeys-rules.sh | sudo tee -a /etc/audit/rules.d/50-auditdsec.rules
#   sudo augenrules --load
#
# Re-run it after adding a user.
set -eu

echo "## generated by gen-sshkeys-rules.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
getent passwd | awk -F: '$3 >= 1000 && $3 < 65534 && $6 != "" { print $6 }' | sort -u | while read -r home; do
    [ -d "$home" ] || continue
    case "$home" in
        /root|/) continue ;;
    esac
    echo "-w ${home}/.ssh -p wa -k ads_sshkeys"
done
